/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#include <stdint.h>
int main(void)
{
    uint32_t *pClkCtrlreg = (uint32_t*)0x40023830;//clock control register.
    uint32_t *pPortDModReg= (uint32_t*)0x40020C00;//base GPIOD.
    uint32_t *pPortDOutReg= (uint32_t*)0x40020C14;//GPIOD's output register.

    //1. enable the clock for GPOID peripheral in the AHB1ENR.
    uint32_t temp = *pClkCtrlreg;//read operation
    temp= temp | 0x08;//modify
    *pClkCtrlreg=temp;//write back
    // this 3 line might be *pClkCtrlreg=*pClkCtrlreg | 0x80 or *pClkCtrlreg |= 0x80

    //2. configure the mode of the IO pin as output.
    //a. clear the 24th and 25th bit positions.(clear)
    *pPortDModReg &= 0xFCFFFFFF;
    //b. set 24th bit as 0 and 25th as 1.(set)
    *pPortDModReg |=0x01000000;

    //3. set 12th sit of the output data register to make I/O pin-12 as High.
    *pPortDOutReg |=0x1000;

    while(1);



}
