/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#include <stdint.h>
int main(void)
{
    uint32_t *pClkCtrlreg = (uint32_t*)0x40023830;//clock control register.
    uint32_t *pPortDModReg= (uint32_t*)0x40020C00;//base GPIOD.
    uint32_t *pPortDOutReg= (uint32_t*)0x40020C14;//GPIOD's output register.

    uint32_t *pPortAModReg= (uint32_t*)0x40020000;
    uint32_t *pPortAInReg = (uint32_t*)0x40020010;
    // enable the clock for GPOID and GPOIA peripherals in the AHB1ENR.
    *pClkCtrlreg |= (1<<3);//0x08 (GPOID)
    *pClkCtrlreg |= (1<<0);//0X00 (GPOIA)

    // configure PD12 as output
    *pPortDModReg &= ~(3<<24);//0xFCFFFFFF
    //b. set 24th bit as 0 and 25th as 1.(set)
    *pPortDModReg |=(1<<24);//0x01000000

    // configure PD0 as output(GPOIA mode register)
    *pPortAModReg &= ~(3<<0);

    while(1)
    {
	// read the pin status of the pin PA0 (GPIOA input data register)
    uint8_t pinStatus = (uint8_t*)(*pPortAInReg & 0x1);//(give only first bit)

    if(pinStatus){
    	//turn on the LED
    	*pPortDOutReg |=(1<<12);//0x1000
    }else{//turn of the LED
    	*pPortDOutReg &=~(1<<12);//0x1000}
    }

    }

}
